"""Correção dos modelos e relacionamentos

Revision ID: 85d204f382f9
Revises: 
Create Date: 2025-01-29 09:42:38.896726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85d204f382f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.drop_index('cnpj')

    op.drop_table('clinica')
    op.drop_table('servicos_profissionais')
    op.drop_table('servicos_clinicas')
    op.drop_table('profissionais_clinicas')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index('cpf')

    op.drop_table('paciente')
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.drop_index('crm')

    op.drop_table('profissional')
    op.drop_table('servico')
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_servico',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado'),
               nullable=False,
               existing_server_default=sa.text("'pendente'"))
        batch_op.drop_constraint('agendamentos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pacientes', ['id_paciente'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('agendamentos_ibfk_1', 'paciente', ['id_paciente'], ['id'])
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado'),
               nullable=True,
               existing_server_default=sa.text("'pendente'"))
        batch_op.alter_column('id_servico',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('servico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_servico', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('tipo_servico', mysql.ENUM('consulta', 'exame'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('profissional',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('especialidade', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('crm', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tipo_contrato', mysql.ENUM('autonomo', 'contratado', 'conveniado'), nullable=False),
    sa.Column('disponibilidade', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valor_consulta', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_exame', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.create_index('crm', ['crm'], unique=True)

    op.create_table('paciente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('rg', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contrato', mysql.VARCHAR(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index('cpf', ['cpf'], unique=True)

    op.create_table('profissionais_clinicas',
    sa.Column('id_profissional', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_clinica', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id'], name='profissionais_clinicas_ibfk_2'),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id'], name='profissionais_clinicas_ibfk_1'),
    sa.PrimaryKeyConstraint('id_profissional', 'id_clinica'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servicos_clinicas',
    sa.Column('id_clinica', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id'], name='servicos_clinicas_ibfk_1'),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], name='servicos_clinicas_ibfk_2'),
    sa.PrimaryKeyConstraint('id_clinica', 'id_servico'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servicos_profissionais',
    sa.Column('id_profissional', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id'], name='servicos_profissionais_ibfk_1'),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], name='servicos_profissionais_ibfk_2'),
    sa.PrimaryKeyConstraint('id_profissional', 'id_servico'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clinica',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.create_index('cnpj', ['cnpj'], unique=True)

    # ### end Alembic commands ###
