"""empty message

Revision ID: d25a40e0918d
Revises: 
Create Date: 2025-02-24 15:49:33.890081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd25a40e0918d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('whatsapp', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_convenio', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_especialidade', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'viúvo'), nullable=False),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('id_especialidade', sa.Integer(), nullable=False),
    sa.Column('registro_profissional', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registro_profissional')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id_profissional', sa.Integer(), nullable=True),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preparo', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('id_profissional', sa.Integer(), nullable=True),
    sa.Column('id_clinica', sa.Integer(), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('servico')
    op.drop_table('agendamento')
    op.drop_table('especialidade')
    op.drop_table('convenio')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index('cpf')

    op.drop_table('paciente')
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.drop_index('registro_profissional')

    op.drop_table('profissional')
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.drop_index('cnpj')

    op.drop_table('clinica')
    with op.batch_alter_table('clinica_profissional', schema=None) as batch_op:
        batch_op.drop_constraint('clinica_profissional_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('clinica_profissional_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profissionais', ['id_profissional'], ['id'])
        batch_op.create_foreign_key(None, 'clinicas', ['id_clinica'], ['id'])

    with op.batch_alter_table('paciente_convenio', schema=None) as batch_op:
        batch_op.drop_constraint('paciente_convenio_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('paciente_convenio_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pacientes', ['id_paciente'], ['id'])
        batch_op.create_foreign_key(None, 'convenios', ['id_convenio'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente_convenio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('paciente_convenio_ibfk_2', 'convenio', ['id_convenio'], ['id'])
        batch_op.create_foreign_key('paciente_convenio_ibfk_1', 'paciente', ['id_paciente'], ['id'])

    with op.batch_alter_table('clinica_profissional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinica_profissional_ibfk_2', 'profissional', ['id_profissional'], ['id'])
        batch_op.create_foreign_key('clinica_profissional_ibfk_1', 'clinica', ['id_clinica'], ['id'])

    op.create_table('clinica',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('whatsapp', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.create_index('cnpj', ['cnpj'], unique=True)

    op.create_table('profissional',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_especialidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registro_profissional', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidade.id'], name='profissional_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.create_index('registro_profissional', ['registro_profissional'], unique=True)

    op.create_table('paciente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('estado_civil', mysql.ENUM('solteiro', 'casado', 'divorciado', 'viúvo'), nullable=False),
    sa.Column('profissao', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index('cpf', ['cpf'], unique=True)

    op.create_table('convenio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_convenio', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('especialidade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_especialidade', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('agendamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_solicitacao', mysql.DATETIME(), nullable=False),
    sa.Column('id_solicitante', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_paciente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_profissional', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_clinica', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_agendamento', mysql.DATETIME(), nullable=False),
    sa.Column('horario', mysql.TIME(), nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinica.id'], name='agendamento_ibfk_4'),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], name='agendamento_ibfk_1'),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissional.id'], name='agendamento_ibfk_3'),
    sa.ForeignKeyConstraint(['id_servico'], ['servico.id'], name='agendamento_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('id_profissional', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_clinica', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('preparo', mysql.TEXT(), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinica.id'], name='servico_ibfk_2'),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissional.id'], name='servico_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('profissionais')
    op.drop_table('pacientes')
    op.drop_table('especialidades')
    op.drop_table('convenios')
    op.drop_table('clinicas')
    # ### end Alembic commands ###
